1. Please use broadcasting or other methods to speed up the following simulation codes. You need to roughly speed it up 5 times as the minimum requirement. (Without speedup, the time used in my computer is 137 seconds, and the improved code uses only 27 seconds.)

In [ ]:
import numpy as np
import time

#only one bullet in the gun
num_test=20000000
num_pos=20
pos_take=tuple(range(10))

start_time=time.time()
np.random.seed(10)
num_lose=0
for nt in range(num_test):
    A=np.zeros(num_pos)
    A[np.random.randint(0,num_pos)]=1

    for n in range(num_pos):
        if A[n]==1:
            if n in pos_take:
                num_lose += 1
            break

print("The lose probability is:", num_lose/num_test)
print("Time:",time.time()-start_time)
print("Number of tests:",num_test)

In [2]:
import numpy as np
import time
import numba as nb

#only one bullet in the gun
@nb.jit()
def main(star_time):
    num_test =20000000
    num_pos=20
    num_pos_2 = int(num_pos/2)
    # pos_take=tuple(range(10))

    np.random.seed(10)
    trial_matrix = np.zeros([num_test, num_pos])
    for nt in range(num_test):
        trial_matrix[nt, np.random.randint(0, num_pos)] = 1

    lose_matrix = trial_matrix[:,:num_pos_2]
    num_lose = lose_matrix.sum()
    print("The lose probability is:", num_lose/num_test)
    print("Time:",time.time()-start_time,'s')
    print("Number of tests:",num_test)

if __name__ == '__main__':
    start_time=time.time()
    main(start_time)


<ipython-input-2-58f57d023b9a>:6: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "main" failed type inference due to: No implementation of function Function(<built-in function zeros>) found for signature:
 
 >>> zeros(list(int64)<iv=[20000000, 20]>)
 
There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload of function 'zeros': File: numba/core/typing/npydecl.py: Line 504.
      With argument(s): '(list(int64)<iv=None>)':
     No match.

During: resolving callee type: Function(<built-in function zeros>)
During: typing of call at <ipython-input-2-58f57d023b9a> (14)


File "<ipython-input-2-58f57d023b9a>", line 14:
def main(star_time):
    <source elided>
    np.random.seed(10)
    trial_matrix = np.zeros([num_test, num_pos])
    ^

  @nb.jit()
<ipython-input-2-58f57d023b9a>:6: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "main" failed type infe

The lose probability is: 0.50013315
Time: 2.3800301551818848
Number of tests: 20000000


2. Similar to `range()`, define a custom function `arange()` that can also accept floating point numbers with optional arguments (start, stop, step) and return a list that contains a sequence of numbers from start (inclusive) to stop (exclusive) by step. Do not use `numpy.arange()` for practicing. The function can automatically change the default step from 1 to -1 when implied. The user will repeatedly input the function to evaluate (quit upon error). Your output should look like this:


    Enter an expression with arange(): arange(stop=0)
    []
    Enter an expression with arange(): arange(stop=5)
    [0, 1, 2, 3, 4]
    Enter an expression with arange(): arange(stop=-5)
    [0, -1, -2, -3, -4]
    Enter an expression with arange(): arange(stop=5.1)
    [0.0, 1.0, 2.0, 3.0, 4.0, 5.0]
    Enter an expression with arange(): arange(-1.1,1.1)
    [-1.1, -0.1, 0.9]
    Enter an expression with arange(): arange(1.1,-1.1)
    [1.1, 0.1, -0.9]
    Enter an expression with arange(): arange(-1,1,0.9)
    [-1.0, -0.1, 0.8]
    Enter an expression with arange(): arange(1,-1,-1/3)
    [1.0, 0.6666666666666666, 0.3333333333333333, 0.0, -0.3333333333333333, -0.6666666666666666]
    Enter an expression with arange(): [i*2 for i in arange(1,2,0.2)]
    [2.0, 2.4, 2.8, 3.2, 3.6]
    Enter an expression with arange():

In [3]:
def arange(start_num = 0, stop = 1, step = 1):

    list = []
    # arange(stop=0)
    if stop == 0:
        return []
    else:
        tmp = start_num
        i = 1
        if (stop < start_num) & (step > 0):
            step *= (-1)
            while tmp > stop :
                list.append(round(tmp,9))
                tmp = start_num + i * step
                i += 1
            return list
        elif (stop < start_num) & (step < 0):
            while tmp > stop :
                list.append(round(tmp,9))
                tmp = start_num + i * step
                i += 1
            return list
        else:
            while tmp < stop :
                list.append(round(tmp,9))
                tmp = start_num + i * step
                i += 1
            return list
if __name__ == '__main__':
    print(arange(stop=0))
    print(arange(stop=5))
    print(arange(stop=-5))
    print(arange(stop =5.1))
    print(arange(-1.1,1.1))
    print(arange(1.1,-1.1))
    print(arange(-1,1,0.9))
    print(arange(1,-1,-1/3))
    print([i*2 for i in arange(1,2,0.2)])


[]
[0, 1, 2, 3, 4]
[0, -1, -2, -3, -4]
[0, 1, 2, 3, 4, 5]
[-1.1, -0.1, 0.9]
[1.1, 0.1, -0.9]
[-1, -0.1, 0.8]
[1, 0.666666667, 0.333333333, 0.0, -0.333333333, -0.666666667]
[2, 2.4, 2.8, 3.2, 3.6]


3. An identity matrix is defined as a square matrix with 1s running from the top left of the square to the bottom right and the rest are 0s. Create a numpy.ndarray that takes an integer n and print the identity matrix of n x n dimensions. For this question, if the integer is negative, return the mirror image of the identity matrix of n x n dimensions. It does not matter if the mirror image is left-right or top-bottom. Incompatible types passed as n should return the string "Error". Your output should look like one of these:


    Enter dimension of identity matrix: 0
    []
***
    Enter dimension of identity matrix: 2
    [[1 0]
     [0 1]]
***
    Enter dimension of identity matrix: -2
    [[0 1]
     [1 0]]

In [4]:
import numpy as np

def identity(n_tmp):
    try:
        n = int(n_tmp)
        if n == 0:
            return []

        elif n > 0:
            initial = np.array([0 for x in range(n)])
            initial[0] = 1
            i = 1
            while i < n:
                lst_tmp = [0 for x in range(n)]
                lst_tmp[i] = 1
                tmp = np.array(lst_tmp)
                initial = np.column_stack((initial, tmp))
                i += 1
            return initial

        else:
            initial = np.array([0 for x in range(-n)])
            initial[-1] = 1
            i = 2
            while i <= (-n):
                lst_tmp = [0 for x in range(-n)]
                lst_tmp[-i] = 1
                tmp = np.array(lst_tmp)
                initial = np.column_stack((initial, tmp))
                i += 1
            return initial

    except ValueError:
        return 'ERROR'


def main():
    n = input('Enter dimension of identity matrix:')

    print(identity(n))
if __name__ == '__main__':
    main()


Enter dimension of identity matrix:-2
[[0 1]
 [1 0]]


4. Create a 3x3 matrix of a tic-tac-toe game as numpy.ndarray called `TicTacToe` and print it out for every turn. All the matrix elements are zeros (0) at first and then filled randomly in position by one (1) first and then two (2) alternatively. The game ends and display "1 wins" or "2 wins" when either side wins the game or "Draw" when completely filled without a winner. Your output should look like this:


    [[0 0 0]
     [0 0 0]
     [0 0 0]]
    After turn 1:
    [[0 0 0]
     [0 0 0]
     [1 0 0]]
    After turn 2:
    [[0 0 0]
     [0 2 0]
     [1 0 0]]
    After turn 3:
    [[0 1 0]
     [0 2 0]
     [1 0 0]]
    After turn 4:
    [[0 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 5:
    [[1 1 0]
     [2 2 0]
     [1 0 0]]
    After turn 6:
    [[1 1 0]
     [2 2 2]
     [1 0 0]]
    2 wins

In [5]:
import numpy as np
import random

def game():
    chess = [0 for i in range(9)]
    initial = [i for i in range(9)]
    win = False
    turn = 1
    print(np.reshape(chess,[3,3]))
    while not win:
        tmp = random.choice(initial)
        chess[tmp] = 1
        initial.remove(tmp)
        print(f'After turn {turn}')
        turn += 1
        print(np.reshape(chess,[3,3]))
        win = win_con(chess)
        if win:
            break
        if len(initial) == 0:
            break
        tmp = random.choice(initial)
        chess[tmp] = 2
        initial.remove(tmp)
        print(f'After turn {turn}')
        turn += 1
        print(np.reshape(chess, [3, 3]))
        win = win_con(chess)
        if win:
            break
    print(f'{winner(chess)} wins')
def win_con(a):
    # a = array.flatten()
    con = ((a[0] == 1 and a[1] == 1 and a[2] == 1) or(a[3] == 1 and a[4] == 1 and a[5] == 1) or
    (a[6] == 1 and a[7] == 1 and a[8] == 1) or
    (a[0] == 1 and a[3] == 1 and a[6] == 1) or
    (a[1] == 1 and a[4] == 1 and a[7] == 1) or
    (a[2] == 1 and a[5] == 1 and a[8] == 1) or
    (a[0] == 1 and a[4] == 1 and a[8] == 1) or
    (a[2] == 1 and a[4] == 1 and a[6] == 1) or
    (a[0] == 2 and a[1] == 2 and a[2] == 2) or
    (a[3] == 2 and a[4] == 2 and a[5] == 2) or
    (a[6] == 2 and a[7] == 2 and a[8] == 2) or
    (a[0] == 2 and a[3] == 2 and a[6] == 2) or
    (a[1] == 2 and a[4] == 2 and a[7] == 2) or
    (a[2] == 2 and a[5] == 2 and a[8] == 2) or
    (a[0] == 2 and a[4] == 2 and a[8] == 2) or
    (a[2] == 2 and a[4] == 2 and a[6] == 2))
    return con

def winner(a):
    con_1 = ((a[0] == 1 and a[1] == 1 and a[2] == 1) or(a[3] == 1 and a[4] == 1 and a[5] == 1) or
    (a[6] == 1 and a[7] == 1 and a[8] == 1) or
    (a[0] == 1 and a[3] == 1 and a[6] == 1) or
    (a[1] == 1 and a[4] == 1 and a[7] == 1) or
    (a[2] == 1 and a[5] == 1 and a[8] == 1) or
    (a[0] == 1 and a[4] == 1 and a[8] == 1) or
    (a[2] == 1 and a[4] == 1 and a[6] == 1))

    con_2 = ((a[0] == 2 and a[1] == 2 and a[2] == 2) or
    (a[3] == 2 and a[4] == 2 and a[5] == 2) or
    (a[6] == 2 and a[7] == 2 and a[8] == 2) or
    (a[0] == 2 and a[3] == 2 and a[6] == 2) or
    (a[1] == 2 and a[4] == 2 and a[7] == 2) or
    (a[2] == 2 and a[5] == 2 and a[8] == 2) or
    (a[0] == 2 and a[4] == 2 and a[8] == 2) or
    (a[2] == 2 and a[4] == 2 and a[6] == 2))

    if con_1:
        return 1
    elif con_2:
        return 2


if __name__ == '__main__':
    game()


[[0 0 0]
 [0 0 0]
 [0 0 0]]
After turn 1
[[0 1 0]
 [0 0 0]
 [0 0 0]]
After turn 2
[[2 1 0]
 [0 0 0]
 [0 0 0]]
After turn 3
[[2 1 1]
 [0 0 0]
 [0 0 0]]
After turn 4
[[2 1 1]
 [0 0 0]
 [0 2 0]]
After turn 5
[[2 1 1]
 [0 0 0]
 [1 2 0]]
After turn 6
[[2 1 1]
 [0 2 0]
 [1 2 0]]
After turn 7
[[2 1 1]
 [0 2 1]
 [1 2 0]]
After turn 8
[[2 1 1]
 [2 2 1]
 [1 2 0]]
After turn 9
[[2 1 1]
 [2 2 1]
 [1 2 1]]
1 wins


5. Now add some AI to question 4 to override choosing a place randomly for each turn in the tic-tac-toe game. First, see if there is a place to take that will win the game. If there is, take that place. Otherwise, see if there is a place the other side can take that will win the game. If there is, take there to block the other side. Otherwise, continue with the randomly selected place remaining. Run the simulation until 1 second is reached. Your output should look like this:


    Probability of 1 wins:
    Probability of 2 wins:
    Probability of draw:
    Games completed:
    Simulation time:

In [3]:

import numpy as np
import random
import time
import numba as nb

def game():
    chess = [0 for i in range(9)]
    initial = [i for i in range(9)]
    win = False
    turn = 1
    result = ''
    # print(np.reshape(chess,[3,3]))
    while not win:
        for i in initial:
            chess_tmp = chess.copy()
            chess_tmp[i] = 1
            if win_con(chess_tmp):
                chess[i] = 1
                win = win_con(chess_tmp)
                # print(f'After turn {turn}')
                turn += 1
                # print(np.reshape(chess,[3,3]))
                break
        if win:
            break
        else:
            defeat = False
            for i in initial:
                chess_tmp = chess.copy()
                chess_tmp[i] = 2
                if win_con(chess_tmp):
                    chess[i] = 1
                    # print(f'After turn {turn}')
                    turn += 1
                    # print(np.reshape(chess,[3,3]))
                    initial.remove(i)
                    defeat = True
                    break
            if len(initial) == 0:
                result = 'draw'
                win = True
                # print(result)
                break
            if not defeat:
                tmp = random.choice(initial)
                chess[tmp] = 1
                initial.remove(tmp)
                # print(f'After turn {turn}')
                turn += 1
                # print(np.reshape(chess,[3,3]))
                win = win_con(chess)
            if len(initial) == 0:
                result = 'draw'
                win = True
                # print(result)
                break

        # =========================================  =========================================
        for i in initial:
            chess_tmp = chess.copy()
            chess_tmp[i] = 2
            if win_con(chess_tmp):
                chess[i] = 2
                win = win_con(chess_tmp)
                # print(f'After turn {turn}')
                turn += 1
                # print(np.reshape(chess,[3,3]))
                break
        if win:
            break
        else:
            defeat = False
            for i in initial:
                chess_tmp = chess.copy()
                chess_tmp[i] = 1
                if win_con(chess_tmp):
                    chess[i] = 2
                    # print(f'After turn {turn}')
                    turn += 1
                    # print(np.reshape(chess,[3,3]))
                    initial.remove(i)
                    defeat = True
                    break
            if len(initial) == 0:
                result = 'draw'
                win = True
                # print(result)
                break
            if not defeat:
                tmp = random.choice(initial)
                chess[tmp] = 2
                initial.remove(tmp)
                # print(f'After turn {turn}')
                turn += 1
                # print(np.reshape(chess,[3,3]))
                win = win_con(chess)
            if len(initial) == 0:
                result = 'draw'
                win = True
                # print(result)
                break

    return winner(chess)

def win_con(a):
    # a = array.flatten()
    con = ((a[0] == 1 and a[1] == 1 and a[2] == 1) or(a[3] == 1 and a[4] == 1 and a[5] == 1) or
    (a[6] == 1 and a[7] == 1 and a[8] == 1) or
    (a[0] == 1 and a[3] == 1 and a[6] == 1) or
    (a[1] == 1 and a[4] == 1 and a[7] == 1) or
    (a[2] == 1 and a[5] == 1 and a[8] == 1) or
    (a[0] == 1 and a[4] == 1 and a[8] == 1) or
    (a[2] == 1 and a[4] == 1 and a[6] == 1) or
    (a[0] == 2 and a[1] == 2 and a[2] == 2) or
    (a[3] == 2 and a[4] == 2 and a[5] == 2) or
    (a[6] == 2 and a[7] == 2 and a[8] == 2) or
    (a[0] == 2 and a[3] == 2 and a[6] == 2) or
    (a[1] == 2 and a[4] == 2 and a[7] == 2) or
    (a[2] == 2 and a[5] == 2 and a[8] == 2) or
    (a[0] == 2 and a[4] == 2 and a[8] == 2) or
    (a[2] == 2 and a[4] == 2 and a[6] == 2))
    return con

def winner(a):
    con_1 = ((a[0] == 1 and a[1] == 1 and a[2] == 1) or(a[3] == 1 and a[4] == 1 and a[5] == 1) or
    (a[6] == 1 and a[7] == 1 and a[8] == 1) or
    (a[0] == 1 and a[3] == 1 and a[6] == 1) or
    (a[1] == 1 and a[4] == 1 and a[7] == 1) or
    (a[2] == 1 and a[5] == 1 and a[8] == 1) or
    (a[0] == 1 and a[4] == 1 and a[8] == 1) or
    (a[2] == 1 and a[4] == 1 and a[6] == 1))

    con_2 = ((a[0] == 2 and a[1] == 2 and a[2] == 2) or
    (a[3] == 2 and a[4] == 2 and a[5] == 2) or
    (a[6] == 2 and a[7] == 2 and a[8] == 2) or
    (a[0] == 2 and a[3] == 2 and a[6] == 2) or
    (a[1] == 2 and a[4] == 2 and a[7] == 2) or
    (a[2] == 2 and a[5] == 2 and a[8] == 2) or
    (a[0] == 2 and a[4] == 2 and a[8] == 2) or
    (a[2] == 2 and a[4] == 2 and a[6] == 2))

    if con_1:
        return 1
    elif con_2:
        return 2
    else:
        return 3

if __name__ == '__main__':
    # winners = game()
    # if winners == 1:
    #     print('1 wins')
    # elif winners == 2:
    #     print('2 wins')
    result = []
    # count = 50000
    count = 0
    start_time = time.time()
    # for i in range(count):
    while (time.time()-start_time) < 1:
        winners = game()
        result.append(winners)
        count += 1
    end_time = time.time()
    count_1 = result.count(1)
    count_2 = result.count(2)
    draw_result = result.count(3)

    print(f'Probability of 1 wins: {count_1 / count}')
    print(f'Probability of 2 wins: {count_2 / count}')
    print(f'Probability of draw: {draw_result / count}')
    print(f'Games completed: {count}')
    print(f'Simulation time: {end_time - start_time}s')

Probability of 1 wins: 0.31138632629849616
Probability of 2 wins: 0.1767976747124984
Probability of draw: 0.5118159989890054
Games completed: 7913
Simulation time: 1.0000660419464111s


6. A cereal company is giving away a prize in each box of cereal and they advertise "Collect all 10 prizes!". Each box of cereal has 1 prize, and each prize is equally likely to appear in any given box. Estimate how many boxes it takes, on average, to get N different prizes using simulation for just 0.1 second for each N. Your output should look like this:


    Total simulation time:

    N    Average boxes
    1    1.0
    2

In [6]:
import random
import numpy as np
import time
N = [i+1 for i in range(10)]
average = []
for i in N:
    count_all = []
    start_time = time.time()
    # for j in range(20000):
    while (time.time() - start_time) < 0.1:
        con = False
        count = 0
        prize_lst = []
        while not con:
            if len(prize_lst) == i:
                con = True
            else:
                new = random.randint(1, 10)
                if new not in prize_lst:
                    prize_lst.append(new)
                count += 1
        count_all.append(count)
    average.append(round(np.mean(count_all),0))

template = '{:>3}\t\t{:<5}'
index = 1
print(template.format('N','Average boxes'))
for i in average:
    print(template.format(index, i))
    index += 1

  N		Average boxes
  1		1.0  
  2		2.0  
  3		3.0  
  4		5.0  
  5		6.0  
  6		8.0  
  7		11.0 
  8		14.0 
  9		19.0 
 10		29.0 
